//! Generated static catalog for the Visual Assets v1 contract.

use crate::{IconContext, IconSpec, WallpaperSpec};

macro_rules! icon {
    ($name:literal, $context:ident, $dir:literal) => {
        IconSpec {
            name: $name,
            context: IconContext::$context,
            relative_path: concat!($dir, "/", $name, ".svg"),
            tintable: true,
        }
    };
}

/// Canonical registry of Nexxus-owned symbolic icons.
pub const ICONS: &[IconSpec] = &[
    icon!("edit-copy", Actions, "actions"),
    icon!("edit-cut", Actions, "actions"),
    icon!("edit-delete", Actions, "actions"),
    icon!("edit-find", Actions, "actions"),
    icon!("edit-paste", Actions, "actions"),
    icon!("list-add", Actions, "actions"),
    icon!("list-remove", Actions, "actions"),
    icon!("media-eject", Actions, "actions"),
    icon!("system-lock-screen", Actions, "actions"),
    icon!("system-log-out", Actions, "actions"),
    icon!("system-reboot", Actions, "actions"),
    icon!("system-search", Actions, "actions"),
    icon!("system-shutdown", Actions, "actions"),
    icon!("view-fullscreen", Actions, "actions"),
    icon!("view-refresh", Actions, "actions"),
    icon!("view-restore", Actions, "actions"),
    icon!("window-close", Actions, "actions"),
    icon!("window-float", Actions, "actions"),
    icon!("window-maximize", Actions, "actions"),
    icon!("window-minimize", Actions, "actions"),
    icon!("window-restore", Actions, "actions"),
    icon!("window-tile", Actions, "actions"),
    icon!("applications-accessories", Categories, "categories"),
    icon!("applications-development", Categories, "categories"),
    icon!("applications-graphics", Categories, "categories"),
    icon!("applications-internet", Categories, "categories"),
    icon!("applications-multimedia", Categories, "categories"),
    icon!("applications-office", Categories, "categories"),
    icon!("applications-other", Categories, "categories"),
    icon!("applications-system", Categories, "categories"),
    icon!("applications-utilities", Categories, "categories"),
    icon!("preferences-audio", Categories, "categories"),
    icon!("preferences-bluetooth", Categories, "categories"),
    icon!("preferences-desktop", Categories, "categories"),
    icon!("preferences-display", Categories, "categories"),
    icon!("preferences-keyboard", Categories, "categories"),
    icon!("preferences-mouse", Categories, "categories"),
    icon!("preferences-notifications", Categories, "categories"),
    icon!("preferences-power", Categories, "categories"),
    icon!("preferences-system", Categories, "categories"),
    icon!("preferences-system-network", Categories, "categories"),
    icon!("preferences-tiling", Categories, "categories"),
    icon!("preferences-workspaces", Categories, "categories"),
    icon!("audio-card", Devices, "devices"),
    icon!("audio-input-microphone", Devices, "devices"),
    icon!("audio-volume-high", Devices, "devices"),
    icon!("audio-volume-muted", Devices, "devices"),
    icon!("battery", Devices, "devices"),
    icon!("bluetooth", Devices, "devices"),
    icon!("drive-harddisk", Devices, "devices"),
    icon!("drive-removable-media", Devices, "devices"),
    icon!("input-keyboard", Devices, "devices"),
    icon!("input-mouse", Devices, "devices"),
    icon!("network-wired", Devices, "devices"),
    icon!("network-wireless", Devices, "devices"),
    icon!("video-display", Devices, "devices"),
    icon!("application-x-generic", MimeTypes, "mimetypes"),
    icon!("audio-x-generic", MimeTypes, "mimetypes"),
    icon!("image-x-generic", MimeTypes, "mimetypes"),
    icon!("package-x-generic", MimeTypes, "mimetypes"),
    icon!("text-x-generic", MimeTypes, "mimetypes"),
    icon!("video-x-generic", MimeTypes, "mimetypes"),
    icon!("folder", Places, "places"),
    icon!("folder-open", Places, "places"),
    icon!("folder-remote", Places, "places"),
    icon!("network-server", Places, "places"),
    icon!("user-bookmarks", Places, "places"),
    icon!("user-desktop", Places, "places"),
    icon!("user-home", Places, "places"),
    icon!("user-trash", Places, "places"),
    icon!("battery-charging", Status, "status"),
    icon!("battery-low", Status, "status"),
    icon!("bluetooth-active", Status, "status"),
    icon!("bluetooth-disabled", Status, "status"),
    icon!("dialog-error", Status, "status"),
    icon!("dialog-information", Status, "status"),
    icon!("dialog-warning", Status, "status"),
    icon!("network-error", Status, "status"),
    icon!("network-offline", Status, "status"),
    icon!("network-online", Status, "status"),
    icon!("notification", Status, "status"),
    icon!("notification-disabled", Status, "status"),
];

/// Initial wallpaper set distributed by the Nexxus asset package.
pub const WALLPAPERS: &[WallpaperSpec] = &[
    WallpaperSpec {
        name: "01-cyber-grid",
        relative_path: "01-cyber-grid.svg",
        category: "cyberpunk",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "02-neon-horizon",
        relative_path: "02-neon-horizon.svg",
        category: "cyberpunk",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "03-data-rain",
        relative_path: "03-data-rain.svg",
        category: "cyberpunk",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "04-steam-foundry",
        relative_path: "04-steam-foundry.svg",
        category: "steampunk",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "05-brass-circuit",
        relative_path: "05-brass-circuit.svg",
        category: "steampunk",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "06-hybrid-forge",
        relative_path: "06-hybrid-forge.svg",
        category: "hybrid",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "07-terminal-city",
        relative_path: "07-terminal-city.svg",
        category: "cyberpunk",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "08-signature-lines",
        relative_path: "08-signature-lines.svg",
        category: "signature",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "09-minimal-hex",
        relative_path: "09-minimal-hex.svg",
        category: "signature",
        width: 1920,
        height: 1080,
    },
    WallpaperSpec {
        name: "10-dark-mountain",
        relative_path: "10-dark-mountain.svg",
        category: "minimal",
        width: 1920,
        height: 1080,
    },
];
